# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('chapter', models.TextField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction', models.BooleanField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GutenbergID',
            fields=[
                ('gutenberg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Gutenberg ID')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_broken_up', models.BooleanField(default=False)),
                ('regex', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FileChapter',
            fields=[
                ('chapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Chapter')),
            ],
            bases=('books.chapter',),
        ),
        migrations.CreateModel(
            name='FileText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Text')),
                ('words', models.FileField(upload_to='')),
                ('is_gutenberg', models.BooleanField()),
            ],
            bases=('books.text',),
        ),
        migrations.CreateModel(
            name='Gutenberg',
            fields=[
                ('html_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.GutenbergID')),
                ('url', models.URLField(default='http://www.gutenberg.org/cache/epub/1232/pg1232.txt')),
                ('html_file', models.FileField(upload_to='')),
                ('parent_text', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.FileText')),
            ],
        ),
        migrations.CreateModel(
            name='InputChapter',
            fields=[
                ('chapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Chapter')),
            ],
            bases=('books.chapter',),
        ),
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Text')),
                ('words', models.TextField()),
            ],
            bases=('books.text',),
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='books.Author'),
        ),
        migrations.AddField(
            model_name='genre',
            name='text',
            field=models.ManyToManyField(null=True, to='books.Text'),
        ),
        migrations.AddField(
            model_name='inputchapter',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.InputText'),
        ),
        migrations.AddField(
            model_name='filechapter',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.FileText'),
        ),
    ]
