# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170215_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('chapter', models.TextField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='FileText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Text')),
                ('words', models.FileField(upload_to='')),
            ],
            bases=('books.text',),
        ),
        migrations.CreateModel(
            name='Gutenberg',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='books.Text')),
                ('html_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(default='http://www.gutenberg.org/cache/epub/1232/pg1232.txt')),
                ('html_file', models.FileField(upload_to='')),
                ('parent_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.FileText')),
            ],
            options={
                'ordering': ('title',),
            },
            bases=('books.text',),
        ),
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Text')),
                ('words', models.TextField()),
            ],
            bases=('books.text',),
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ManyToManyField(null=True, to='books.Author'),
        ),
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='default title', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileChapter',
            fields=[
                ('chapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Chapter')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.FileText')),
            ],
            bases=('books.chapter',),
        ),
        migrations.CreateModel(
            name='InputChapter',
            fields=[
                ('chapter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Chapter')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.InputText')),
            ],
            bases=('books.chapter',),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookChapter',
        ),
        migrations.DeleteModel(
            name='BookFile',
        ),
    ]
