# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_gutenbergid_html_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gutenbergid',
            old_name='id',
            new_name='html_id',
        ),
    ]
