# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170215_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction', models.BooleanField()),
                ('genre', models.CharField(max_length=100)),
                ('text', models.ManyToManyField(null=True, to='books.Text')),
            ],
        ),
    ]
