# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetext',
            name='is_gutenberg',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
