# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170206_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFile',
            fields=[
                ('html_id', models.IntegerField(primary_key=True, serialize=False)),
                ('html_file', models.FileField(upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='GutenbergID',
        ),
    ]
