# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170206_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlfile',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='html_file',
            field=models.FileField(default='default_html_file', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='html_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='HTMLFile',
        ),
    ]
