# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_filetext_is_gutenberg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='regex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
