# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170206_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='chapter',
            field=models.CharField(max_length=200),
        ),
    ]
