# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170218_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gutenbergid',
            name='id',
        ),
        migrations.AlterField(
            model_name='gutenbergid',
            name='g_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
