# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170209_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfile',
            name='book_title',
        ),
        migrations.AddField(
            model_name='bookfile',
            name='book',
            field=models.OneToOneField(default='default cascade for book file relationship', on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
            preserve_default=False,
        ),
    ]
