# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170209_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookFile'),
        ),
    ]
