# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170218_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gutenberg',
            name='html_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.GutenbergID'),
        ),
        migrations.AlterField(
            model_name='gutenberg',
            name='text_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Text'),
        ),
    ]
