# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170209_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='book',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
